### ISSUE TITLE
TaskExecutionException

### ISSUE THREAD

**Issue by drfreaky** [palantir/gradle-graal#26]
After I have added the plugin to my project I get a TaskExecutionException. I am using Gradle 4.10.2 and plugin version 0.2.0-2-g4155cf9.

```
./gradlew nativeImage --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nativeImage'.
> No value has been specified for this provider.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':nativeImage'.
        at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.resolve(DefaultTaskProperties.java:86)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.resolveMutations(DefaultTaskExecutionPlan.java:610)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getResolvedMutationInfo(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNext(DefaultTaskExecutionPlan.java:552)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$2.transform(DefaultTaskPlanExecutor.java:174)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$2.transform(DefaultTaskPlanExecutor.java:161)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:161)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
        at com.palantir.gradle.graal.NativeImageTask.lambda$new$0(NativeImageTask.java:61)
        at org.gradle.api.internal.provider.TransformBackedProvider.map(TransformBackedProvider.java:32)
        at org.gradle.api.internal.provider.AbstractMappingProvider.get(AbstractMappingProvider.java:45)
        at org.gradle.api.internal.provider.AbstractMappingProvider.get(AbstractMappingProvider.java:45)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
        at org.gradle.util.DeferredUtil.unpack(DeferredUtil.java:39)
        at org.gradle.api.internal.tasks.DefaultCacheableTaskOutputFilePropertySpec.getOutputFile(DefaultCacheableTaskOutputFilePropertySpec.java:49)
        at org.gradle.api.internal.tasks.properties.GetOutputFilesVisitor.visitOutputFileProperty(GetOutputFilesVisitor.java:44)
        at org.gradle.api.internal.tasks.properties.CompositePropertyVisitor.visitOutputFileProperty(CompositePropertyVisitor.java:49)
        at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:35)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:62)
        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:39)
        at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.resolve(DefaultTaskProperties.java:77)
        ... 11 more


* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by dansanduleac** [comment]
The error could be better, but you haven't configured the `outputName` in the `graal` extension.

**Comment by drfreaky** [comment]
:+1:

**Comment by tobit800** [comment]
I had the same issue, but I don´t know how to set the `outputName`.
I tried `graal {
  mainClassName = 'de.demo.main.ConsoleApp'
  outputName = 'consoleapp'
}`

But then I get the following error:

`14:15:12: Executing task 'nativeImage'...


FAILURE: Build failed with an exception.

* Where:
Build file 'D:\workspaces\bankjob\build.gradle' line: 36

* What went wrong:
A problem occurred evaluating root project 'schnittstellen'.
> Cannot set the value of read-only property 'outputName' for object of type com.palantir.gradle.graal.GraalExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 235ms
14:15:13: Task execution finished 'nativeImage'.
`

**Comment by dvdfmiller** [comment]
Answer use mainClass instead of mainClassName and remove the "="s like this:
`graal {
 mainClass 'de.demo.main.ConsoleApp' 
 outputName 'consoleapp'
 }`

And you solve the error:
`Cannot set the value of read-only property 'outputName' for object of type com.palantir.gradle.graal.GraalExtension.`
